// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.utmos.dev/support",
            "email": "support@utmos.dev"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/devices": {
            "get": {
                "description": "List devices with pagination and optional filtering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "List devices",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by vendor",
                        "name": "vendor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by device type",
                        "name": "device_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ListDevicesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new device with the provided information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Create a new device",
                "parameters": [
                    {
                        "description": "Device information",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.CreateDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.DeviceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/devices/sn/{sn}": {
            "get": {
                "description": "Get device details by serial number",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Get a device by serial number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device Serial Number",
                        "name": "sn",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.DeviceResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/devices/{id}": {
            "get": {
                "description": "Get device details by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Get a device by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.DeviceResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update device information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Update a device",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Device information to update",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.UpdateDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.DeviceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a device by ID",
                "tags": [
                    "devices"
                ],
                "summary": "Delete a device",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/services/call": {
            "post": {
                "description": "Invoke a service call on a device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Invoke a service call",
                "parameters": [
                    {
                        "description": "Service call request",
                        "name": "call",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ServiceCallRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ServiceCallResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/services/calls/device/{device_sn}": {
            "get": {
                "description": "List service calls for a specific device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "List service calls for a device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device Serial Number",
                        "name": "device_sn",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ListServiceCallsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/services/calls/{id}": {
            "get": {
                "description": "Get service call details by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Get a service call by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service Call ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ServiceCallResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/services/calls/{id}/cancel": {
            "post": {
                "description": "Cancel a pending service call",
                "tags": [
                    "services"
                ],
                "summary": "Cancel a service call",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service Call ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ServiceCallResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/telemetry/{device_sn}": {
            "get": {
                "description": "Query telemetry data for a device within a time range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Query telemetry data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device Serial Number",
                        "name": "device_sn",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "-1h",
                        "description": "Start time (RFC3339)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "now",
                        "description": "Stop time (RFC3339)",
                        "name": "stop",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Measurement name",
                        "name": "measurement",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.TelemetryQueryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/telemetry/{device_sn}/aggregate": {
            "get": {
                "description": "Query aggregated telemetry data for a device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Query aggregated telemetry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device Serial Number",
                        "name": "device_sn",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "-24h",
                        "description": "Start time (RFC3339)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "now",
                        "description": "Stop time (RFC3339)",
                        "name": "stop",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "1h",
                        "description": "Aggregation window",
                        "name": "window",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "mean",
                        "description": "Aggregation function (mean, max, min, sum)",
                        "name": "fn",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to aggregate",
                        "name": "field",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.TelemetryQueryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/telemetry/{device_sn}/latest": {
            "get": {
                "description": "Get the latest telemetry data for a device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Get latest telemetry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device Serial Number",
                        "name": "device_sn",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.LatestTelemetryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api_handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_utmos_utmos_pkg_models.DeviceStatus": {
            "type": "string",
            "enum": [
                "online",
                "offline",
                "unknown"
            ],
            "x-enum-varnames": [
                "DeviceStatusOnline",
                "DeviceStatusOffline",
                "DeviceStatusUnknown"
            ]
        },
        "internal_api_handler.CreateDeviceRequest": {
            "type": "object",
            "required": [
                "device_name",
                "device_sn",
                "device_type"
            ],
            "properties": {
                "device_name": {
                    "type": "string"
                },
                "device_sn": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "gateway_sn": {
                    "type": "string"
                },
                "thing_model_id": {
                    "type": "integer"
                },
                "vendor": {
                    "type": "string"
                }
            }
        },
        "internal_api_handler.DeviceResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "device_name": {
                    "type": "string"
                },
                "device_sn": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "gateway_sn": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_online_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_utmos_utmos_pkg_models.DeviceStatus"
                },
                "thing_model_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                }
            }
        },
        "internal_api_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_api_handler.LatestTelemetryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "device_sn": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_api_handler.ListDevicesResponse": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_handler.DeviceResponse"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "internal_api_handler.ListServiceCallsResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "service_calls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_handler.ServiceCallResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_api_handler.ServiceCallRequest": {
            "type": "object",
            "required": [
                "device_sn",
                "method",
                "vendor"
            ],
            "properties": {
                "call_type": {
                    "type": "string"
                },
                "device_sn": {
                    "type": "string"
                },
                "max_retries": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "vendor": {
                    "type": "string"
                }
            }
        },
        "internal_api_handler.ServiceCallResponse": {
            "type": "object",
            "properties": {
                "bid": {
                    "type": "string"
                },
                "call_type": {
                    "type": "string"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "device_sn": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "max_retries": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "retry_count": {
                    "type": "integer"
                },
                "sent_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tid": {
                    "type": "string"
                },
                "vendor": {
                    "type": "string"
                }
            }
        },
        "internal_api_handler.TelemetryPoint": {
            "type": "object",
            "properties": {
                "fields": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "internal_api_handler.TelemetryQueryResponse": {
            "type": "object",
            "properties": {
                "device_sn": {
                    "type": "string"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api_handler.TelemetryPoint"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_api_handler.UpdateDeviceRequest": {
            "type": "object",
            "properties": {
                "device_name": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "gateway_sn": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_utmos_utmos_pkg_models.DeviceStatus"
                },
                "thing_model_id": {
                    "type": "integer"
                },
                "vendor": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "UMOS IoT Platform API",
	Description:      "UMOS IoT Platform RESTful API for device management and service calls",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
