run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - tests
    - mocks
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

linters-settings:
  goimports:
    local-prefixes: github.com/utmos/utmos
  goconst:
    min-len: 3
    min-occurrences: 2
  misspell:
    locale: US
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - gofmt
    - misspell
    - gocyclo
    - dupl
    - gocritic
    - goconst
    - typecheck
    - unconvert
    - prealloc
    - exportloopref
    - gosec
    - revive
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gochecknoinits
    - gocognit
    - godot
    - godox
    - goerr113
    - goheader
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacer
    - lll
    - maintidx
    - makezero
    - maligned
    - noctx
    - nolintlint
    - paralleltest
    - promlinter
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - structcheck
    - stylecheck
    - tagliatelle
    - thelper
    - unparam
    - varcheck
    - whitespace
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocritic
    - path: pkg/models
      linters:
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0

